name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build packages
        run: |
          bun run --cwd packages/compute-protocol build
          bun run --cwd packages/compute build
          bun run --cwd packages/github build
          bun run --cwd packages/slack build
          bun run --cwd packages/model-intent build
          bun run --cwd packages/blink build

      - name: Run formatter check
        run: bun run format --check

      - name: Run type checking
        run: bun run typecheck

      - name: Run tests
        run: bun test
